/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/HomePage`; params?: Router.UnknownInputParams; } | { pathname: `/InquiredPropertiesPage`; params?: Router.UnknownInputParams; } | { pathname: `/ListPropertyPage`; params?: Router.UnknownInputParams; } | { pathname: `/ManagePropertiesPage`; params?: Router.UnknownInputParams; } | { pathname: `/ProfilePage`; params?: Router.UnknownInputParams; } | { pathname: `/PropertyDetailsPage`; params?: Router.UnknownInputParams; } | { pathname: `/SavedPropertiesPage`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/HomePage`; params?: Router.UnknownOutputParams; } | { pathname: `/InquiredPropertiesPage`; params?: Router.UnknownOutputParams; } | { pathname: `/ListPropertyPage`; params?: Router.UnknownOutputParams; } | { pathname: `/ManagePropertiesPage`; params?: Router.UnknownOutputParams; } | { pathname: `/ProfilePage`; params?: Router.UnknownOutputParams; } | { pathname: `/PropertyDetailsPage`; params?: Router.UnknownOutputParams; } | { pathname: `/SavedPropertiesPage`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/HomePage${`?${string}` | `#${string}` | ''}` | `/InquiredPropertiesPage${`?${string}` | `#${string}` | ''}` | `/ListPropertyPage${`?${string}` | `#${string}` | ''}` | `/ManagePropertiesPage${`?${string}` | `#${string}` | ''}` | `/ProfilePage${`?${string}` | `#${string}` | ''}` | `/PropertyDetailsPage${`?${string}` | `#${string}` | ''}` | `/SavedPropertiesPage${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/HomePage`; params?: Router.UnknownInputParams; } | { pathname: `/InquiredPropertiesPage`; params?: Router.UnknownInputParams; } | { pathname: `/ListPropertyPage`; params?: Router.UnknownInputParams; } | { pathname: `/ManagePropertiesPage`; params?: Router.UnknownInputParams; } | { pathname: `/ProfilePage`; params?: Router.UnknownInputParams; } | { pathname: `/PropertyDetailsPage`; params?: Router.UnknownInputParams; } | { pathname: `/SavedPropertiesPage`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
    }
  }
}
